inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
    - db/**/*
    - bin/**
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Max: 150

Style/AlignParameters:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 10

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'

Style/PerlBackrefs:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
